[package]
name = "yavv"
edition = "2021"

[dependencies]
nalgebra = "*"
winit = "*"
wgpu = "*"
tinyjson = "*"
zune-core = "*"
zune-image = { version = "*", default-features = false, features = [ "png", "jpeg", "metadata", "simd" ] }

[profile.dev.package."*"]
opt-level = 1
debug = false
overflow-checks = false

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
